### ISSUE TITLE
Instant error after running the executable compiled using the included Makefile.mth

### ISSUE THREAD

**Issue by FelixSpr** [spiemonte/LeonardYM#1]
@daschaich and me have been trying to get this code running, but we instantly get the following error after running the executable (from the included Makefile.mth) using the pure gauge configuration file:
$ ./leonardYM.exe --configfile=config_pure_gauge.cfg
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
Aborted (core dumped)

The main modification that we have done (https://github.com/FelixSpr/LeonardYM/tree/master), was to rewrite the path to the Boost libraries explicitly in the Makefile (.mth and .mpi) in line 19 to enable compilation:

- $(CPP) $(CPPFLAGS) $(OBJECTS) -o ./build/leonardYM.exe -lboost_program_options

+$(CPP) $(CPPFLAGS) $(OBJECTS) -o ./build/leonardYM.exe -L/opt/gridware/depots/e2b91392/el7/pkg/libs/boost/1.60.0/gcc-5.5.0+openmpi-1.10.7+python-2.7.8/lib -lboost_program_options

We are using version 3.3.9 for Eigen and version 1.60.0 for Boost.

Do you have an idea what the problem could be and how we can fix it?
Should we use a different version of Eigen and/or Boost?

**Comment by ghost** [comment]
Everything works fine for me, Eigen 3.3.7 boost 1.74.0, it seems to me that you have an old version of the boost libraries.

**Comment by spiemonte** [comment]
In principle, the code should work with boost version >= 1.5 (Eigen is not related to this issue), however, I had many problems in the past with boost_program_option. Which operating system are you using? 

My suggestions:

* The problem should be related to <a href=https://github.com/spiemonte/LeonardYM/blob/master/source/io/StorageParameters.h#L23>this part of the code</a> that reads an option from the configuration file, can you try to place a breakpoint there?
* Sometimes accidentally some invisible character could land in the config file, could you try to see if, by mistake, you have changed something?
* I see that you are using gcc-5.5 (from your path gcc-5.5.0+openmpi-1.10.7), however, that compiler version Is pretty old. I am using gcc-7.x (that is also not really a recent version, I should try to compile the code with gcc-10).

**Comment by FelixSpr** [comment]
Thanks for the quick reply. I am trying to run the program on a Linux cluster.

- I set a break point at line 23 in StorageParameters.h and got the following message:


(gdb) run --configfile=config_measurements.cfg
The program being debugged has been started already.
Start it from the beginning? (y or n) y

Starting program: /mnt/data1/users/springfx/LeonardYMmyfork/LeonardYM/build/leonardYM.exe --configfile=config_measurements.cfg
warning: File "/opt/gridware/depots/e2b91392/el7/pkg/compilers/gcc/5.5.0/lib64/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed

Program received signal SIGABRT, Aborted.
0x00007ffff6af0337 in raise () from /usr/lib64/libc.so.6


- I tried multiple different config files and I get the same error.

- I compiled the code using gcc 7.4.0 (although I still use the same boost library  libs/boost/1.60.0/gcc-5.5.0+openmpi-1.10.7+python-2.7.8) and got the same error as before.

**Comment by spiemonte** [comment]
After a quick search on google, apparently it is a problem related to multiple version of boost present in your system (compiling against a version, linking with another one, see <a href=https://stackoverflow.com/questions/35382902/boost-program-options-throws-character-conversion-failed>here</a>, <a href=https://github.com/leela-zero/leela-zero/issues/6>here</a> and <a href=https://github.com/patrikhuber/eos/issues/55>here</a>). 

Please check in your system and in your include path which version are you including and link statically directly program_option against that version (for instance, try to specify the full path to libboost_program_options.a).

**Comment by daschaich** [comment]
The issue did turn out to be some configuration problems with the Boost installations on our institutional cluster.  We eventually figured out how to work around them, so this issue can be closed.  Thanks for the help and guidance!  Boost is new and mysterious to us both.
