### ISSUE TITLE
Landau Gauge Fixing is broken for SU(N) HMC other than N=3

### ISSUE THREAD

**Issue by ghost** [spiemonte/LeonardYM#4]
Hi @spiemonte, i have a problem.

When running the program compiled with NUMCOLORS=3, Landau Gauge Fixing converges well and produces correct result.
### SU(3) HMC
`LandauGaugeFixing::Maximal functional at step 2970: 11716.7`
`LandauGaugeFixing::   convergence: 4.46612e-11`
`LandauGaugeFixing::Final deviation from the Landau gauge: 3.40372e-30`
`Delta energy in metropolis: -3.14283 - accepted!`

In other cases (N=2,4,5) Landau Gauge Fixing seems to work incorrectly.

### SU(2) HMC
`LandauGaugeFixing::Maximal functional at step 0: 3.58455e+54`
`LandauGaugeFixing::Maximal functional at step 30: 3.58455e+54`
`LandauGaugeFixing::   convergence: 0`
`LandauGaugeFixing::Final deviation from the Landau gauge: 9.12747e+103`
`Delta energy in metropolis: nan - rejected!`

### SU(4) HMC
`LandauGaugeFixing::Maximal functional at step 0: 3.14898e+06`
`LandauGaugeFixing::Maximal functional at step 30: 3.14898e+06`
`LandauGaugeFixing::   convergence: 0`
`LandauGaugeFixing::Final deviation from the Landau gauge: 38858`
`Delta energy in metropolis: 5.32543e+31 - rejected!`

### SU(5) HMC
`LandauGaugeFixing::Maximal functional at step 0: 710780`
`LandauGaugeFixing::Maximal functional at step 30: 710780`
`LandauGaugeFixing::   convergence: 0`
`LandauGaugeFixing::Final deviation from the Landau gauge: 19740.5`
`Delta energy in metropolis: 1.32531e+26 - rejected!`

### SU(2) CM
However, if instead of the PureGaugeHMC you enable PureGaugeCM, then deviation from Landau Gauge is ok...
`LandauGaugeFixing::Maximal functional at step 0: 9554.54`
`LandauGaugeFixing::Maximal functional at step 30: 9554.54`
`LandauGaugeFixing::   convergence: 0`
`LandauGaugeFixing::Final deviation from the Landau gauge: 4.1916e-17`

All runs used the same configuration file - pure.txt

[logSU2GaugeFixCM.txt](https://github.com/spiemonte/LeonardYM/files/9351703/logSU2GaugeFixCM.txt)
[logSU2GaugeFixHMC.txt](https://github.com/spiemonte/LeonardYM/files/9351704/logSU2GaugeFixHMC.txt)
[logSU3GaugeFixHMC.txt](https://github.com/spiemonte/LeonardYM/files/9351705/logSU3GaugeFixHMC.txt)
[logSU4GaugeFixHMC.txt](https://github.com/spiemonte/LeonardYM/files/9351706/logSU4GaugeFixHMC.txt)
[logSU5GaugeFixHMC.txt](https://github.com/spiemonte/LeonardYM/files/9351707/logSU5GaugeFixHMC.txt)
[pure.txt](https://github.com/spiemonte/LeonardYM/files/9351708/pure.txt)

**Comment by spiemonte** [comment]
Hi,

I think the issue is related to the gauge transformation on the links required for gauge fixing and the HMC equation of motion, the two combined can become unstable. Can you try to just run HMC, save the configurations, and then afterwards run the gauge fixing?

**Comment by ghost** [comment]
@spiemonte, In general, the results are as follows - If you write gauge configurations in Münster format, the gauge fixing works correctly. If you try to write them in Leonard format, then the gauge fixing does not work correctly.

Can you explain what the Münster format is and why the gauge fixing only works with the Münster format?
Also, as seen from warning message - `OuputSweep::munster_format not implemented for NC>3!`.


[logSU2leonard.txt](https://github.com/spiemonte/LeonardYM/files/9470451/logSU2leonard.txt)
[logSU2muenster.txt](https://github.com/spiemonte/LeonardYM/files/9470452/logSU2muenster.txt)
[logSU4leonard.txt](https://github.com/spiemonte/LeonardYM/files/9470454/logSU4leonard.txt)
[meas.txt](https://github.com/spiemonte/LeonardYM/files/9470455/meas.txt)
[pure.txt](https://github.com/spiemonte/LeonardYM/files/9470456/pure.txt)

**Comment by ghost** [comment]
@spiemonte, Well, what are your thoughts on this? Can it be fixed?
