### ISSUE TITLE
SU(N) Gauge Fixing does not converge

### ISSUE THREAD

**Issue by ghost** [spiemonte/LeonardYM#5]
@spiemonte Hello. Re-opening the topic, because the old one has stagnated. I've been waiting for a response from you for two months, do you even read your github? But the problem didn't go away.
I don't understand why everything works for SU(3) but not for N>3, although over relaxation algorithm seems to be correct. Where is the catch?

**Comment by spiemonte** [comment]
@magCIx: I have fixed the Landau gauge, apparently the eigenvalue decomposition does not work for SU(N), perhaps it would be better to consider the SVD for the projection to the gauge group in the overrelaxation procedure. I can get a convergence for SU(4) now with something like 20000 steps.

Concerning the timing of my replies and possible future issues, please refer to the terms of the GPL license, in particular section 15: "THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW".
